### ISSUE TITLE
Feature request: add a LICENSE

### ISSUE THREAD

**Issue by mcorossigo** [mattiasgeniar/the-infinite-file-download#1]
Hello @mattiasgeniar 
Not that I really wanted to resurrect this old repo,
but can I ask you to add a LICENSE to it?
Possibly an open one, like MIT.

I wanted to use it for some tests and since http://infinite-download.ma.ttias.be/ seems always out of bandwith, I would love to self-host it.

Still, I'm a little scared of your `full team of lawyers` so..

**Comment by mattiasgeniar** [comment]
Haha :-)

Sure thing, I added the MIT license in 2fc6779.

Mattias
